#ifndef __RNSKeyCodeMapping_h__
#define __RNSKeyCodeMapping_h__
#include <iostream>
typedef enum _rns_key
{
    RNS_KEY_Right,
    RNS_KEY_Left,
    RNS_KEY_Up,
    RNS_KEY_Down,
    RNS_KEY_Select,
    RNS_KEY_PowerOff,
    RNS_KEY_AudioMedia,
    RNS_KEY_Menu,
    RNS_KEY_AudioLowerVolume,
    RNS_KEY_AudioRaiseVolume,
    RNS_KEY_CHANNEL_Up,
    RNS_KEY_CHANNEL_Down,
    RNS_KEY_HELP,
    RNS_KEY_Refresh,
    RNS_KEY_AudioStop,
    RNS_KEY_AudioPlay,
    RNS_KEY_AudioPause,
    RNS_KEY_Back,
    RNS_KEY_AudioNext,
    RNS_KEY_AudioRewind,
    RNS_KEY_AudioForward,
    RNS_KEY_AudioPrev,
    RNS_KEY_Green,
    RNS_KEY_Red,
    RNS_KEY_Blue,
    RNS_KEY_Yellow,
    RNS_KEY_1,
    RNS_KEY_2,
    RNS_KEY_3,
    RNS_KEY_4,
    RNS_KEY_5,
    RNS_KEY_6,
    RNS_KEY_7,
    RNS_KEY_8,
    RNS_KEY_9,
    RNS_KEY_0,
    RNS_KEY_TV_RAD,
    RNS_KEY_AUDIOREACORD,
    RNS_KEY_AUD,
    RNS_KEY_Cancel,
    RNS_KEY_Mute,
    RNS_KEY_GUIA,
    RNS_KEY_UNKNOWN
}rns_key_t;

static std::string RNSKeyMap[RNS_KEY_UNKNOWN+1]={
"Right", //RNS_KEY_RIGHT
"Left",  //RNS_KEY_LEFT
"Up",
"Down",
"Select",
"PowerOff",
"AudioMedia"
"Menu",
"AudioLowerVolume",
"AudioRaiseVolume",
"CHANNEL_Up",
"CHANNEL_Down",
"HELP",
"Refresh",
"AudioStop",
"AudioPlay",
"AudioPause",
"Back",
"AudioNext",
"AudioRewind",
"AudioForward",
"AudioPrev",
"AudioPrev",
"Green",
"Red",
"Blue",
"Yellow",
"1",
"2",
"3",
"4",
"5",
"6",
"7",
"8",
"9",
"0",
"TV/RAD",
"AUDIOREACORD",
"AUD",
"cancel",
"Mute",
"GUIA",
"UnKown"};

#endif// __RNSKeyCodeMapping_h__
